// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace BuilderBuddy.Migrations
{
    [DbContext(typeof(Context))]
    [Migration("20220723194035_NewProjectValues")]
    partial class NewProjectValues
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "6.0.6");

            modelBuilder.Entity("BuilderBuddy.Models.Project", b =>
                {
                    b.Property<int>("ProjectID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<decimal>("BoxesOfScrews")
                        .HasColumnType("TEXT");

                    b.Property<decimal>("DrywallCost")
                        .HasColumnType("TEXT");

                    b.Property<decimal>("DrywallSheets")
                        .HasColumnType("TEXT");

                    b.Property<decimal>("JointCompoundCost")
                        .HasColumnType("TEXT");

                    b.Property<decimal>("JointTapeCost")
                        .HasColumnType("TEXT");

                    b.Property<decimal>("PoundsOfJointCompound")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("ProjectDate")
                        .HasColumnType("TEXT");

                    b.Property<string>("ProjectName")
                        .HasColumnType("TEXT");

                    b.Property<decimal>("RollsOfTape")
                        .HasColumnType("TEXT");

                    b.Property<decimal>("ScrewsCost")
                        .HasColumnType("TEXT");

                    b.HasKey("ProjectID");

                    b.ToTable("Project");

                    b.HasData(
                        new
                        {
                            ProjectID = 1,
                            BoxesOfScrews = 0m,
                            DrywallCost = 0m,
                            DrywallSheets = 0m,
                            JointCompoundCost = 0m,
                            JointTapeCost = 0m,
                            PoundsOfJointCompound = 0m,
                            ProjectDate = new DateTime(2022, 7, 23, 15, 40, 35, 686, DateTimeKind.Local).AddTicks(6643),
                            ProjectName = "Lincoln's Cabin",
                            RollsOfTape = 0m,
                            ScrewsCost = 0m
                        });
                });

            modelBuilder.Entity("BuilderBuddy.Models.Wall", b =>
                {
                    b.Property<int>("WallID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("Height")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Length")
                        .HasColumnType("INTEGER");

                    b.Property<int>("ProjectID")
                        .HasColumnType("INTEGER");

                    b.HasKey("WallID");

                    b.HasIndex("ProjectID");

                    b.ToTable("Wall");

                    b.HasData(
                        new
                        {
                            WallID = 1,
                            Height = 8,
                            Length = 24,
                            ProjectID = 1
                        },
                        new
                        {
                            WallID = 2,
                            Height = 8,
                            Length = 16,
                            ProjectID = 1
                        },
                        new
                        {
                            WallID = 3,
                            Height = 8,
                            Length = 24,
                            ProjectID = 1
                        },
                        new
                        {
                            WallID = 4,
                            Height = 8,
                            Length = 16,
                            ProjectID = 1
                        });
                });

            modelBuilder.Entity("BuilderBuddy.Models.Wall", b =>
                {
                    b.HasOne("BuilderBuddy.Models.Project", "Project")
                        .WithMany("Walls")
                        .HasForeignKey("ProjectID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Project");
                });

            modelBuilder.Entity("BuilderBuddy.Models.Project", b =>
                {
                    b.Navigation("Walls");
                });
#pragma warning restore 612, 618
        }
    }
}
